# Generated by Django 4.1.7 on 2023-03-08 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_remove_member_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Faol emas'), (2, 'Faol'), (3, 'Mavjud emas'), (4, 'Yangi qo`shilmoqchi')], default=2),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
