# Generated by Django 4.1.7 on 2023-03-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_member_gender_alter_member_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='permission',
            field=models.SmallIntegerField(blank=True, choices=[(0, "Yangi qo'shilgan"), (1, "O'quvchi"), (2, 'Mentor'), (3, 'Admin')], default=0, null=True),
        ),
    ]
