# Generated by Django 4.1.7 on 2023-03-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_member_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Boshlanmoqda'), (2, 'Davom Qilyabdi'), (3, 'Guruh Yopilgan')], default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Chiqib ketgan'), (2, 'Faol'), (3, 'Mavjud emas'), (4, 'Yangi qo`shilmoqchi')], default=2),
        ),
    ]
