# Generated by Django 4.1.7 on 2023-03-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_group_status_alter_member_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Ism Familiya')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('telegram', models.CharField(blank=True, max_length=70, null=True, verbose_name='Telegram username')),
                ('extra_contact', models.CharField(blank=True, max_length=256, null=True, verbose_name="Qo'shimcha Contact")),
                ('additional', models.TextField(blank=True, null=True, verbose_name='Qiziqishingiz haqida qisqacha')),
                ('view', models.BooleanField(default=False)),
                ('contacted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Yangi Yozilmoqchi',
                'verbose_name_plural': "Kursga Yozilmoqchi bo'lganlar",
            },
        ),
    ]
