# Generated by Django 4.1.7 on 2023-03-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_interested'),
    ]

    operations = [
        migrations.AddField(
            model_name='interested',
            name='via',
            field=models.CharField(blank=True, default='Aniq emas', max_length=128, null=True),
        ),
    ]
