# Generated by Django 4.1.7 on 2023-03-17 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_interested_via'),
    ]

    operations = [
        migrations.AddField(
            model_name='interested',
            name='who_contacted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.member'),
        ),
    ]
